Repository python-discord/snekbox, pull requests merged in 2020-11, with the labels that each got.

#78 Update to Python 3.9
  .flake8
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  config/snekbox.cfg
  docker/base.Dockerfile
Labels: area: dependencies, priority: 2 - normal, type: feature

#79 Migrate to GitHub Actions and GitHub Container Registry
  .github/workflows/lint-test-build-push.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  azure-pipelines.yml
  ci/build.yml
  ci/lint-test.yml
  ci/push.yml
  ci/setup.yml
  docker-compose.yml
  docker/Dockerfile
  docker/venv.Dockerfile
  scripts/check_dockerfiles.sh
  scripts/dev.sh
Labels: area: CI, priority: 0 - critical

#81 Limit STDOUT to prevent OOM events in container
  README.md
  config/snekbox.cfg
  snekbox/nsjail.py
  tests/test_nsjail.py
Labels: area: backend, priority: 0 - critical, type: bug
