Repository python-discord/snekbox, pull requests merged in 2020-02, with the labels that each got.

#55 Configure a proper chroot jail for NsJail
  .dockerignore
  README.md
  docker-compose.yml
  docker/venv.Dockerfile
  scripts/.profile
  scripts/dev.sh
  snekbox.cfg
  snekbox/nsjail.py
  tests/test_nsjail.py
Labels: bug

#62 Install Pipfile into system interpreter
  Pipfile.lock
  docker/venv.Dockerfile
  scripts/.profile
  snekbox.cfg
Labels: area: CI, status: needs review, type: bug

#54 CI Improvements
  azure-pipelines.yml
  ci/build.yml
  ci/lint-test.yml
  ci/push.yml
  ci/setup.yml
  scripts/check_dockerfiles.sh
Labels: area: CI, status: WIP, type: feature

#59 Use port mapping, change container name to snekbox.
  ci/setup.yml
  docker-compose.yml
  scripts/dev.sh
Labels: area: dev env, status: waiting for author, type: feature
