Repository python-discord/snekbox, pull requests merged in 2020-03, with the labels that each got.

#65 Add sentry integration
  Pipfile
  Pipfile.lock
  snekbox/__init__.py
Labels: area: backend, priority: 2 - normal, type: feature

#67 Update contributor doc
  CONTRIBUTING.md
Labels: area: docs, type: feature

#68 Document a simpler way to run snekbox
  README.md
  snekbox/nsjail.py
Labels: area: docs, priority: 3 - low, status: needs review, type: feature

#69 Fix venv being created in Dockerfile
  .dockerignore
  Pipfile
  README.md
  config/gunicorn.conf.py
  config/snekbox.cfg
  docker/Dockerfile
  docker/venv.Dockerfile
  scripts/.profile
  snekbox/nsjail.py
Labels: area: CI, priority: 2 - normal, status: needs review, type: bug

#70 add --dev flag to readme
  README.md
Labels: area: docs, type: bug
